num1=int(input("Enter first number: "))
num2=int(input("Enter second number: "))
print("Sum of",num1,"and",num2,"is ",num1+num2)
print("Difference of",num1,"and",num2,"is ",num1-num2)
print("Product of",num1,"and",num2,"is ",num1*num2)
print("Quotient of",num1,"and",num2,"is ",num1/num2)
print("Remainder of",num1,"and",num2,"is ",num1%num2)
print("Floor division of",num1,"and",num2,"is ",num1//num2)
